---

- name: Configure Galaxy Server Secret
  include_tasks: combine_galaxy_settings.yml

- name: Use DB fields encryption key as the Django SECRET_KEY
  set_fact:
    pulp_combined_settings: "{{ pulp_combined_settings | combine({'secret_key': db_fields_encryption_secret_contents['resources'][0]['data']['database_fields.symmetric.key'] | b64decode}) }}"
  no_log: "{{ no_log }}"
  when: pulp_combined_settings.secret_key is not defined

- name: Include redis role
  include_role:
    name: redis
  when: pulp_combined_settings.cache_enabled

- include_tasks:
    file: sso-configuration.yml
  when:
    - sso_secret is defined
    - sso_secret | length

- name: Configure Galaxy Server Secret
  include_tasks: galaxy_server_secret.yml
